package ua.gov.diia.ui_base.components.infrastructure.event

object UIActionKeysCompose {

    //atom
    const val TEXT_WITH_PARAMETERS = "onTextWithParametersClick"
    const val BUTTON_REGULAR = "onButtonClick"
    const val BTN_PLAIN_ATM = "onBtnPlainAtmClick"
    const val BUTTON_ALTERNATIVE = "onAltButtonClick"
    const val CHECKBOX_REGULAR = "onCheckboxClick"
    const val RADIO_BUTTON = "onRadioButtonClick"
    const val NUM_BUTTON = "onNumButtonClick"
    const val NUM_BUTTON_REMOVE = "onNumRemoveButtonClick"
    const val TOUCH_ID_BUTTON = "touchIdButton"
    const val CODE_INPUT_ATOM = "codeInputAtom"
    const val LOAD_ACTION_ATOM = "loadActionAtom"
    const val LOAD_ACTION_ATOM_DOWNLOAD = "loadActionAtomResolutionDownload"
    const val LOAD_ACTION_ATOM_RECEIPT = "LoadActionAtomReceipt"
    const val TICKER_ATOM_CLICK = "onTickerClick"
    const val CLOSE_BUTTON = "onCloseButton"
    const val LINK_ATM = "linkAtm"
    const val REFRESH_BUTTON = "onRefreshButton"
    const val BUTTON_CIRCLED = "onButtonCircled"
    const val ARTICLE_PIC_ATM = "articlePicAtm"
    const val BTN_PLAIN_ICON_ATM = "btnPlainIconAtm"
    const val SMALL_ICON_ATM_DATA = "smallIconAtm"
    const val DOUBLE_ICON_ATM_DATA = "doubleIconAtm"
    const val ICON_ATM_DATA = "iconAtm"
    const val CLOSE_ACTION = "close"

    //molecule
    const val RADIO_BTN_GROUP_ORG = "radioBtnGroupOrg"
    const val SINGLE_CHOICE_MLCL = "radioGroupMolecule"
    const val TOOLBAR_NAVIGATION_BACK = "navBack"
    const val TOOLBAR_CONTEXT_MENU = "contextMenu"
    const val LIST_ITEM_CLICK = "onListItemClick"
    const val LIST_ITEM_ALTERNATIVE_CLICK = "onListItemAlternativeClick"
    const val TEXT_INPUT = "textInput"
    const val DATE_INPUT = "dateInput"
    const val INPUT_FORM = "inputForm"
    const val SEARCH_INPUT = "searchInput"
    const val TABLE_HEADING_MOLECULE = "tableHeadingMolecule"
    const val HORIZONTAL_TABLE_ITEM = "horizontalTableItem"
    const val VERTICAL_TABLE_ITEM = "verticalTableItem"
    const val PRIMARY_TABLE_ITEM = "primaryTableItem"
    const val TABLE_BLOCK_ORG = "tableBlockOrg"
    const val ACCORDION_MOLECULE = "accordionMolecule"
    const val QUANTITY_INPUT_MOLECULE = "quantityInputMolecule"
    const val CHIP_TABS_MOLECULE = "chipTabsMolecule"
    const val INPUT_NUMBER_LARGE_MLC = "inputNumberLargeMlc"
    const val OPEN_SIGNING_HISTORY = "navToSigningHistory"
    const val MENU_ITEM_CLICK = "onMenuItemClick"
    const val PS_ITEM_CLICK = "onPublicServiceItemClick"
    const val TEXT_LABEL_MLC = "textLabelMlc"
    const val TEXT_LABEL_CONTAINER_MLC = "textLabelContainerMlc"
    const val TITLE_LABEL_MLC = "titleLabelMlc"
    const val RADIO_BTN_MLC = "radioBtnMlc"
    const val ICON_CARD_MLC = "iconCardMlc"
    const val HALVED_CARD_MLC = "halvedCardMlc"
    const val SMALL_NOTIFICATION_MLC = "smallNotificationMlc"
    const val BLACK_CARD_MLC = "blackCardMlc"
    const val WHITE_CARD_MLC = "whiteCardMlc"
    const val BTN_ICON_ROUNDED_MLC = "btnIconRoundedMlc"
    const val DOC_NUMBER_COPY = "docNumberCopy"
    const val DOC_NUMBER_COPY_WHITE = "docNumberCopyWhite"
    const val DOC_PAGE_SELECTED = "page_selected"
    const val CARD_MLC = "cardMlc"


    const val TOGGLE_BUTTON_MOLECULE = "toggleButtonMolecule"
    const val WHITE_MENU_CARD_MLC = "whiteMenuCardMlc"
    const val DOC_COVER_MLD = "docCoverMlc"
    const val TITLE_GROUP_MLC = "titleGroupMlc"
    const val LIST_ITEM_MLC = "listItemMlc"


    const val CHECKBOX_GROUP_MOLECULE = "checkboxGroupMolecule"
    const val SHEET_NAVIGATION_BAR_MOLECULE = "sheetNavigationBarMolecule"
    const val DETAILS_TEXT_DESCRIPTION_MOLECULE = "detailsTextDescriptionMolecule"
    const val IMAGE_CARD_MLC = "imageCardMlc"
    const val VERTICAL_CARD_MLC = "verticalCardMlc"

    /*Default action keys*/
    const val CARD_PRIMARY_BTN_ACTION = "onCardPrimaryBtnActionClick"
    const val CARD_SECONDARY_BTN_ACTION = "onCardSecondaryBtnActionClick"
    const val BOTTOM_SHEET_DISMISS = "bottomSheetDismiss"

    //organism
    const val SINGLE_CHOICE_WITH_SEARCH_ORGANISM = "singleChoiceWithSearchOrganism"
    const val SINGLE_CHOICE_WITH_ALT_ORGANISM = "singleChoiceWithAltOrganism"
    const val MULTI_CHOICE_GROUP_ORGANISM = "multiChoiceGroupOrganism"
    const val MULTI_CHOICE_ICON_GROUP_ORGANISM = "multiChoiceIconGroupOrganism"
    const val MULTI_CHOICE_GROUP_ORGANISM_ACCORDION_HEADER =
        "multiChoiceGroupOrganismAccordionHeader"
    const val SINGLE_CHOICE_WITH_BUTTON_ORGANISM = "singleChoiceWithButtonOrganism"
    const val PIN_CREATED_NUM_BUTTON_ORGANISM = "pinCreatedNumButtonOrganism"
    const val PIN_CLEARED_NUM_BUTTON_ORGANISM = "pinClearedNumButtonOrganism"
    const val TOP_GROUP_ORG = "topGroupOrg"
    const val QR_SHARE_ORG = "qrShareOrg"
    const val CHECKBOX_BTN_ORG = "checkboxBtnOrg"
    const val DOC_ELLIPSE_MENU = "ellipseMenu"
    const val DOC_STACK = "docStack"
    const val DOC_CARD_FLIP = "docCardFlip"
    const val DOC_CODE_ORG_DATA = "docCodeOrgData"
    const val DOC_CARD_FORCE_FLIP = "docCardForceFlip"
    const val DOC_BUTTON_HEADING_DOC = "docButtonHeadingOrg"
    const val DOC_CARD_SWIPE_FINISHED = "swipeFinished"
    const val DOC_ORG_DATA = "docOrgData"
    const val ADD_DOC_ORG = "addDocOrg"
    const val CHANGE_DOC_ORDER = "changeDocOrder"
    const val LIST_ITEM_GROUP_ORG = "listItemGroupOrg"
    const val LIST_ITEM_BORDERED_GROUP_ORG = "listItemBorderedGroupOrg"


    const val SMALL_NOTIFICATION_CAROUSEL_ORG = "smallNotificationCarouselOrg"
    const val HALVED_CARD_CAROUSEL_ORG = "halvedCardCarouselOrg"
    const val BTN_ICON_ROUNDED_GROUP_ORG = "btnIconRoundedGroupOrg"
    const val VERTICAL_CARD_CAROUSEL_ORG = "verticalCardCarouselOrg"
    const val ARTICLE_PIC_CAROUSEL_ORG = "articlePicCarouselOrg"
    const val MEDIA_TITLE_ORG = "mediaTitleOrg"

    const val SELECTOR_ORG = "selectorOrg"

    //loading
    const val PAGE_LOADING_CIRCULAR = "pageLoadingCircular"
    const val PAGE_LOADING_TRIDENT = "pageLoadingTrident"
    const val PAGE_LOADING_TRIDENT_WITH_BACK_NAVIGATION = "pageLoadingTridentWithBackNavigation"
    const val PAGE_LOADING_TRIDENT_WITH_UI_BLOCKING = "pageLoadingTridentWithUIBlocking"
    const val PAGE_LOADING_LINEAR_PAGINATION = "pageLoadingLinearPagination"
    const val PAGE_LOADING_LINEAR_WITH_LABEL = "pageLoadingLinearWithLabel"

    //item actions
    const val ITEM_ACTION_ORDER_EXTRACT = "orderExtract"
    const val ITEM_ACTION_FAQ = "faq"
    const val ITEM_DOWNLOAD_EXTRACT = "downloadExtract"
    const val ITEM_REQUEST_PERMISSION = "requestPermission"
    const val ITEM_MAP_POINT = "mapPoint"
    const val ITEM_MAP_UNSELECT_POINT = "mapUnselectPoint"
    const val ITEM_MAP_ROUTE = "createRoute"
    const val ITEM_POINT_DETAILS = "openDetails"
    const val ITEM_WATER_MARK_MAP_CLICK = "mapWatermarkClick"
    const val ITEM_MAP_STABLE_POS = "mapStablePosition"
    const val ITEM_POINTS_APPLIED = "mapPointsAddedToMap"
    const val ITEM_REGION_NAV_APPLIED = "navigationToRegionId"
}
