package ua.gov.diia.ui_base.components.infrastructure.event

object UIActionKeysCompose {

    //atom
    const val TEXT_WITH_PARAMETERS = "onTextWithParametersClick"
    const val BUTTON_REGULAR = "onButtonClick"
    const val BTN_PLAIN_ATM = "onBtnPlainAtmClick"
    const val BUTTON_ALTERNATIVE = "onAltButtonClick"
    const val BUTTON_WHITE_ADDITIONAL = "onBtnWhiteAdditional"
    const val CHECKBOX_REGULAR = "onCheckboxClick"
    const val RADIO_BUTTON = "onRadioButtonClick"
    const val NUM_BUTTON = "onNumButtonClick"
    const val NUM_BUTTON_REMOVE = "onNumRemoveButtonClick"
    const val TOUCH_ID_BUTTON = "touchIdButton"
    const val CODE_INPUT_ATOM = "codeInputAtom"
    const val LOAD_ACTION_ATOM = "loadActionAtom"
    const val BTN_LOAD_PLAIN_ICON_ATM = "btnLoadPlainIconAtm"
    const val LOAD_ACTION_ATOM_DOWNLOAD = "loadActionAtomResolutionDownload"
    const val LOAD_ACTION_ATOM_RECEIPT = "LoadActionAtomReceipt"
    const val TICKER_ATOM_CLICK = "onTickerClick"
    const val LARGE_TICKER_ATOM_CLICK = "onLargeTickerClick"
    const val CLOSE_BUTTON = "onCloseButton"
    const val LINK_ATM = "linkAtm"
    const val REFRESH_BUTTON = "onRefreshButton"
    const val BUTTON_CIRCLED = "onButtonCircled"
    const val ARTICLE_PIC_ATM = "articlePicAtm"
    const val ARTICLE_VIDEO_MLC = "articleVideoMlc"
    const val BTN_PLAIN_ICON_ATM = "btnPlainIconAtm"
    const val SMALL_ICON_ATM_DATA = "smallIconAtm"
    const val LARGE_ICON_ATM_DATA = "largeIconAtm"
    const val TEXT_LABEL_ATM_DATA = "textLabelAtm"
    const val SLIDE_BAR_ATM = "slideBarAtm"


    const val SMALL_PIC_ATM_DATA = "smallPicAtm"
    const val DOUBLE_ICON_ATM_DATA = "doubleIconAtm"
    const val ICON_ATM_DATA = "iconAtm"
    const val ICON_URL_ATM = "iconUrlAtm"
    const val USER_PICTURE_ATM = "userPictureAtm"
    const val CLOSE_ACTION = "close"
    const val CALENDAR_ITEM_ATM = "calendarItemAtm"
    const val CALENDAR_ITEM_MONTH_ATM = "calendarItemMonthAtm"
    const val CALENDAR_ITEM_FORWARD = "calendarItemForward"
    const val CALENDAR_ITEM_BACKWARD = "calendarItemBackward"
    const val CALENDAR_ITEM_UPDATE_DATE = "calendarItemUpdateDate"
    const val CALENDAR_ITEM_REFRESH_CALENDAR = "calendarItemRefreshCalendar"
    const val BTN_SEMI_LIGHT_ATM = "btnSemiLightAtm"
    const val BTN_LINK_ATM = "btnLinkAtm"


    //molecule
    const val RADIO_BTN_GROUP_ORG = "radioBtnGroupOrg"
    const val SINGLE_CHOICE_MLCL = "radioGroupMolecule"
    const val TOOLBAR_NAVIGATION_BACK = "navBack"
    const val TOOLBAR_CONTEXT_MENU = "contextMenu"
    const val LIST_ITEM_CLICK = "onListItemClick"
    const val LIST_ITEM_ALTERNATIVE_CLICK = "onListItemAlternativeClick"
    const val TEXT_INPUT = "textInput"
    const val DATE_INPUT = "dateInput"
    const val INPUT_FORM = "inputForm"
    const val SEARCH_INPUT = "searchInput"
    const val CHIP_BLACK_GROUP_ORG = "chipBlackGroupOrg"
    const val TABLE_MAIN_HEADING_MLC = "tableMainHeadingMlc"
    const val TABLE_SECONDARY_HEADING_MLC = "tableSecondaryHeadingMlc"
    const val HORIZONTAL_TABLE_ITEM = "horizontalTableItem"
    const val VERTICAL_TABLE_ITEM = "verticalTableItem"
    const val PRIMARY_TABLE_ITEM = "primaryTableItem"
    const val TABLE_BLOCK_ORG = "tableBlockOrg"
    const val TABLE_BLOCK_ACCORDION_ORG = "tableBlockAccordionOrg"
    const val PHOTO_GROUP_ORG = "photoGroupOrg"
    const val TABLE_ITEM_CHECKBOX_MLC = "tableItemCheckboxMlc"

    const val ACCORDION_MOLECULE = "accordionMolecule"
    const val QUANTITY_INPUT_MOLECULE = "quantityInputMolecule"
    const val CHIP_TABS_MOLECULE = "chipTabsMolecule"
    const val CHIP_MLC = "chipMlc"
    const val CHIP_BLACK_MLC = "chipBlackMlc"
    const val INPUT_NUMBER_LARGE_MLC = "inputNumberLargeMlc"
    const val OPEN_SIGNING_HISTORY = "navToSigningHistory"
    const val MENU_ITEM_CLICK = "onMenuItemClick"
    const val PS_ITEM_CLICK = "onPublicServiceItemClick"
    const val TEXT_LABEL_MLC = "textLabelMlc"
    const val TEXT_LABEL_CONTAINER_MLC = "textLabelContainerMlc"
    const val TITLE_LABEL_MLC = "titleLabelMlc"
    const val RADIO_BTN_MLC = "radioBtnMlc"
    const val ICON_CARD_MLC = "iconCardMlc"
    const val HALVED_CARD_MLC = "halvedCardMlc"
    const val SMALL_NOTIFICATION_MLC = "smallNotificationMlc"
    const val BLACK_CARD_MLC = "blackCardMlc"
    const val WHITE_CARD_MLC = "whiteCardMlc"
    const val BTN_ICON_ROUNDED_MLC = "btnIconRoundedMlc"
    const val DOC_NUMBER_COPY = "docNumberCopy"
    const val DOC_NUMBER_COPY_WHITE = "docNumberCopyWhite"
    const val DOC_PAGE_SELECTED = "page_selected"
    const val CARD_MLC = "cardMlc"
    const val CARD_MLC_V2 = "cardMlcV2"
    const val USER_CARD_MLC = "userCardMlc"
    const val CHIP_TIME_MLC = "chipTimeMlc"
    const val CURRENT_TIME_MLC = "currentTimeMlc"
    const val QR_CODE_MLC = "qrCodeMlc"
    const val BAR_CODE_MLC = "barCodeMlc"
    const val DASHBOARD_CARD_MLC = "dashboardCardMlc"

    const val TOGGLE_BUTTON_MOLECULE = "toggleButtonMolecule"
    const val WHITE_MENU_CARD_MLC = "whiteMenuCardMlc"
    const val DOC_COVER_MLC = "docCoverMlc"
    const val TITLE_GROUP_MLC = "titleGroupMlc"
    const val LIST_ITEM_MLC = "listItemMlc"
    const val LIST_ITEM_UPLOAD_MLC = "listItemMlc"
    const val CONTROL_BUTTON_MIC_MOLECULE = "controlMlcMic"
    const val CONTROL_BUTTON_OUTPUT_MOLECULE = "controlMlcOutput"
    const val CONTROL_BUTTON_CAMERA_FLIP_MOLECULE = "controlMlcCameraFlip"
    const val SMALL_CHECK_ICON_MLC = "smallCheckIconMlc"

    const val CHECKBOX_GROUP_MOLECULE = "checkboxGroupMolecule"
    const val DOC_SERIE_INPUT = "docSerieInput"
    const val DOC_NUMBER_INPUT = "docNumberInput"
    const val SHEET_NAVIGATION_BAR_MOLECULE = "sheetNavigationBarMolecule"
    const val DETAILS_TEXT_DESCRIPTION_MOLECULE = "detailsTextDescriptionMolecule"
    const val IMAGE_CARD_MLC = "imageCardMlc"
    const val LOOPING_VIDEO_PLAYER_CARD_MLC = "loopingVideoPlayerCardMlc"

    const val VERTICAL_CARD_MLC = "verticalCardMlc"

    const val INPUT_NUMBER_MLC = "inputNumberMlc"
    const val TIMER_MLC = "timerMlc"
    const val TEXT_LABEL_MLC_TIMER_IS_EXPIRED = "textLabelMlcTimerIsExpired"
    const val INPUT_TEXT_MULTILINE_MLC = "inputTextMultilineMlc"

    const val INPUT_PHONE_MLC = "inputPhoneMlc"
    const val INPUT_PHONE_CODE_ORG = "inputPhoneCodeOrg"
    const val INPUT_PHONE_CODE_ORG_COUNTRY_CODE = "inputPhoneCodeOrg_CountryCode"

    /*Default action keys*/
    const val CARD_PRIMARY_BTN_ACTION = "onCardPrimaryBtnActionClick"
    const val CARD_SECONDARY_BTN_ACTION = "onCardSecondaryBtnActionClick"
    const val BOTTOM_SHEET_DISMISS = "bottomSheetDismiss"

    //organism
    const val SINGLE_CHOICE_WITH_SEARCH_ORGANISM = "singleChoiceWithSearchOrganism"
    const val SINGLE_CHOICE_WITH_ALT_ORGANISM = "singleChoiceWithAltOrganism"
    const val MULTI_CHOICE_GROUP_ORGANISM = "multiChoiceGroupOrganism"
    const val MULTI_CHOICE_ICON_GROUP_ORGANISM = "multiChoiceIconGroupOrganism"
    const val MULTI_CHOICE_GROUP_ORGANISM_ACCORDION_HEADER =
        "multiChoiceGroupOrganismAccordionHeader"
    const val SINGLE_CHOICE_WITH_BUTTON_ORGANISM = "singleChoiceWithButtonOrganism"
    const val PIN_CREATED_NUM_BUTTON_ORGANISM = "pinCreatedNumButtonOrganism"
    const val PIN_CLEARED_NUM_BUTTON_ORGANISM = "pinClearedNumButtonOrganism"
    const val TOP_GROUP_ORG = "topGroupOrg"
    const val CHECKBOX_BTN_ORG = "checkboxBtnOrg"
    const val CHECKBOX_BTN_WHITE_ORG = "checkboxBtnWhiteOrg"
    const val DOC_ELLIPSE_MENU = "ellipseMenu"
    const val DOC_STACK = "docStack"
    const val DOC_CARD_FLIP = "docCardFlip"
    const val DOC_CODE_ORG_DATA = "docCodeOrgData"
    const val DOC_CARD_FORCE_FLIP = "docCardForceFlip"
    const val DOC_BUTTON_HEADING_DOC = "docButtonHeadingOrg"
    const val DOC_CARD_SWIPE_FINISHED = "swipeFinished"
    const val DOC_ORG_DATA = "docOrgData"
    const val DOC_ORG_DATA_UPDATE_DOC = "docOrgDataUpdateDoc"
    const val ADD_DOC_ORG = "addDocOrg"
    const val CHANGE_DOC_ORDER = "changeDocOrder"
    const val LIST_ITEM_GROUP_ORG = "listItemGroupOrg"
    const val LIST_ITEM_BORDERED_GROUP_ORG = "listItemBorderedGroupOrg"
    const val VERIFICATION_CODES_ORG = "verificationCodesOrg"
    const val SHARING_CODES_ORG = "sharingCodesOrg"
    const val TOGGLE_BUTTON_GROUP_ORG = "toggleButtonGroupOrg"
    const val RADIO_BTN_WITH_ALT_ORG = "radioBtnWithAltOrg"
    const val DASHBOARD_CARD_TILE_ORG = "dashboardCardTileOrg"
    const val BACKGROUND_WHITE_ORG = "backgroundWhiteOrg"

    const val SMALL_NOTIFICATION_CAROUSEL_ORG = "smallNotificationCarouselOrg"
    const val HALVED_CARD_CAROUSEL_ORG = "halvedCardCarouselOrg"
    const val BTN_ICON_ROUNDED_GROUP_ORG = "btnIconRoundedGroupOrg"
    const val VERTICAL_CARD_CAROUSEL_ORG = "verticalCardCarouselOrg"
    const val CARD_HORIZONTAL_SCROLL_ORG = "cardHorizontalScrollOrg"
    const val IMAGE_CARD_CAROUSEL_ORG = "imageCardCarouselOrg"

    const val ARTICLE_PIC_CAROUSEL_ORG = "articlePicCarouselOrg"
    const val MEDIA_TITLE_ORG = "mediaTitleOrg"
    const val MEDIA_UPLOAD_GROUP_ORG = "mediaUploadGroupOrg"
    const val SINGLE_MEDIA_UPLOAD_GROUP_ORG = "singleMediaUploadGroupOrg"
    const val FILE_UPLOAD_GROUP_ORG = "groupFilesAddOrg"
    const val MEDIA_GROUP_ORG = "mediaGroupOrg"
    const val BTN_FLASH_ON_OFF = "flash"


    const val SELECTOR_ORG = "selectorOrg"
    const val CALENDAR_ORG = "calendarOrg"
    const val INPUT_DATE_TIME_ORG = "inputDateTimeOrg"
    const val INPUT_TIME_MLC = "inputTimeMlc"
    const val INPUT_DATE_MLC = "inputDateMlc"

    //loading
    const val PAGE_LOADING_CIRCULAR = "pageLoadingCircular"
    const val PAGE_LOADING_TRIDENT = "pageLoadingTrident"
    const val PAGE_LOADING_TRIDENT_WITH_BACK_NAVIGATION = "pageLoadingTridentWithBackNavigation"
    const val PAGE_LOADING_TRIDENT_WITH_UI_BLOCKING = "pageLoadingTridentWithUIBlocking"
    const val PAGE_LOADING_LINEAR_PAGINATION = "pageLoadingLinearPagination"
    const val PAGE_LOADING_LINEAR_WITH_LABEL = "pageLoadingLinearWithLabel"
    const val PAGE_LOADING_LINEAR_WITHOUT_BACK_BTN_WITH_LABEL =
        "pageLoadingLinearWithoutBackBtnWithLabel"

    //item actions
    const val ITEM_ACTION_ORDER_EXTRACT = "orderExtract"
    const val ITEM_ACTION_FAQ = "faq"
    const val ITEM_DOWNLOAD_EXTRACT = "downloadExtract"
    const val ITEM_REQUEST_PERMISSION = "requestPermission"
    const val ITEM_MAP_POINT = "mapPoint"
    const val ITEM_MAP_UNSELECT_POINT = "mapUnselectPoint"
    const val ITEM_MAP_ROUTE = "createRoute"
    const val ITEM_POINT_DETAILS = "openDetails"
    const val ITEM_WATER_MARK_MAP_CLICK = "mapWatermarkClick"
    const val ITEM_MAP_STABLE_POS = "mapStablePosition"
    const val ITEM_MAP_POINTS_LIST = "mapListRoute"
    const val ITEM_POINTS_APPLIED = "mapPointsAddedToMap"
    const val ITEM_REGION_NAV_APPLIED = "navigationToRegionId"
    const val ITEM_MOVE_TO_POS_APPLIED = "navigationToPosition"
    const val ITEM_HANG_UP = "hangUpAction"
    const val ITEM_FACE_DET_CONFIGURED = "faceDetectorConfigured"
    const val ON_SCANNING_BARCODE_DETECTED = "onScanningBarcodeDetected"

}