package ua.gov.diia.core.models.document.docgroups.v2

enum class QrCheckStatus {
    STATUS_LOAD,
    STATUS_DONE,
    STATUS_DONE_ENG,

    STATUS_DOC_NOT_LOADED_ERROR,
    STATUS_CODE_NO_REGISTRY,

    STATUS_QR_CODE_TIME_OUT,

    STATUS_NO_NETWORK,
    STATUS_CODE_TIME_OUT,
    STATUS_UNKNOWN_CODE_TYPE,
    STATUS_CERT_VERIFICATION_INVALID,
    STATUS_CERT_VERIFICATION_EXPIRED,
}